from enum import StrEnum


class FocusIndicator(StrEnum):
    """Os indicadores que a pesquisa Focus pergunta hoje."""

    IPCA = "ipca"
    IPCA_ADMINISTERED = "ipca_administered"
    IPCA_FREE = "ipca_free"
    IPCA_SERVICES = "ipca_services"
    IPCA_INDUSTRIAL_GOODS = "ipca_industrial_goods"
    IPCA_FOOD_AT_HOME = "ipca_food_at_home"
    EXCHANGE_RATE = "exchange_rate"
    IGPM = "igpm"
    UNEMPLOYMENT = "unemployment"
    SELIC = "selic"
    GDP = "gdp"
    GDP_AGRICULTURE = "gdp_agriculture"
    GDP_INDUSTRY = "gdp_industry"
    GDP_SERVICES = "gdp_services"
    GDP_HOUSEHOLD_CONSUMPTION = "gdp_household_consumption"
    GDP_GOVERNMENT_CONSUMPTION = "gdp_government_consumption"
    GDP_INVESTMENT = "gdp_investment"
    GDP_EXPORTS = "gdp_exports"
    GDP_IMPORTS = "gdp_imports"
    PRIMARY_BALANCE = "primary_balance"
    NOMINAL_BALANCE = "nominal_balance"
    NET_DEBT = "net_debt"
    GROSS_DEBT = "gross_debt"
    CURRENT_ACCOUNT = "current_account"
    TRADE_BALANCE = "trade_balance"
    EXPORTS = "exports"
    IMPORTS = "imports"
    FDI = "fdi"
