import type { ConceptId } from "@/shared/concepts/concept";
import type { SeriesId } from "@/shared/lib/series-labels";

/** O conceito que explica cada série. Uma série nova no backend só compila depois de
ganhar o conceito dela aqui. */
export const conceptBySeries: Record<SeriesId, ConceptId> = {
  ipca_general: "ipca",
  ipca_food: "ipca-group",
  ipca_housing: "ipca-group",
  ipca_household: "ipca-group",
  ipca_apparel: "ipca-group",
  ipca_transport: "ipca-group",
  ipca_health: "ipca-group",
  ipca_personal: "ipca-group",
  ipca_education: "ipca-group",
  ipca_communication: "ipca-group",
  free_prices: "free-prices",
  administered_prices: "administered-prices",
  services_prices: "services-inflation",
  inpc: "inpc",
  minimum_wage: "minimum-wage",
  inflation_target: "inflation-target",
  selic_target: "selic",
  dollar_month_end: "ptax",
  current_account_gdp: "current-account",
  fdi_gdp: "fdi",
  reserves: "international-reserves",
  gdp_usd_12m: "share-of-gdp",
  iip_assets: "international-investment-position",
  iip_liabilities: "international-investment-position",
  nominal_deficit: "nominal-balance",
  primary_deficit: "primary-balance",
  nominal_interest: "nominal-interest",
  primary_deficit_central: "primary-balance",
  primary_deficit_regional: "primary-balance",
  primary_deficit_state_owned: "primary-balance",
  nominal_interest_central: "nominal-interest",
  nominal_interest_regional: "nominal-interest",
  nominal_interest_state_owned: "nominal-interest",
  net_debt: "net-debt",
  net_debt_brl: "net-debt",
  gross_debt: "gross-debt",
  gdp_12m: "nominal-gdp-growth",
  federal_debt_maturity: "average-maturity",
  gdp_growth_4q: "gdp",
  ibc_br: "ibc-br",
  unemployment_rate: "unemployment-rate",
  credit_cost: "credit-cost",
  concessions_business: "credit-concessions",
  concessions_households: "credit-concessions",
};
