import type { DiagramSpec } from "@/shared/components/diagram/diagram-spec";

export const targetSpec: DiagramSpec = {
  height: 380,
  width: 740,
  label:
    "Diagrama de quem fixa a meta de inflação, como ela é perseguida e o que acontece quando é descumprida",
  groupColors: { rule: "var(--bridge-rate)", miss: "var(--bridge-money)" },
  nodes: [
    {
      id: "cmn",
      title: "CMN",
      subtitle: "Conselho Monetário Nacional: fixa a meta e o intervalo",
      x: 10,
      y: 30,
      height: 80,
    },
    {
      id: "bc",
      title: "Banco Central",
      subtitle: "persegue a meta mexendo na Selic",
      concept: "copom",
      x: 280,
      y: 30,
    },
    {
      id: "ipca",
      title: "IPCA em 12 meses",
      subtitle: "comparado com a faixa todo mês",
      concept: "rolling-12m",
      x: 550,
      y: 30,
    },
    {
      id: "inside",
      title: "Dentro da faixa",
      subtitle: "meta cumprida",
      accent: "var(--bridge-rate)",
      x: 550,
      y: 230,
    },
    {
      id: "out",
      title: "6 meses seguidos fora",
      subtitle: "meta descumprida",
      accent: "var(--bridge-money)",
      x: 280,
      y: 230,
    },
    {
      id: "letter",
      title: "Nota e carta aberta",
      subtitle: "ao Ministro da Fazenda: causas, medidas e prazo",
      x: 10,
      y: 230,
      height: 80,
    },
  ],
  edges: [
    {
      from: "cmn",
      to: "bc",
      group: "rule",
      text: "O Conselho Monetário Nacional fixa a meta e o intervalo de tolerância, por proposta do Ministro da Fazenda. Desde 2025 a meta é contínua: vale para qualquer janela de 12 meses, e não só para dezembro.",
      bend: 0,
    },
    {
      from: "bc",
      to: "ipca",
      group: "rule",
      text: "O Banco Central, pelo Copom, sobe ou corta a Selic para levar a inflação à meta.",
      bend: 0,
    },
    {
      from: "ipca",
      to: "inside",
      group: "rule",
      text: "Todo mês, o IPCA em 12 meses é comparado com a faixa. Dentro dela, a meta está cumprida.",
      bend: 0,
    },
    {
      from: "ipca",
      to: "out",
      group: "miss",
      text: "Se ele fica fora da faixa por seis meses seguidos, a meta foi descumprida.",
      bend: 0,
    },
    {
      from: "out",
      to: "letter",
      group: "miss",
      text: "Aí o Banco Central explica em público: uma nota no Relatório de Política Monetária e uma carta aberta ao Ministro da Fazenda, com as causas, as medidas e o prazo para voltar à faixa.",
      bend: 0,
    },
    {
      from: "letter",
      to: "bc",
      group: "miss",
      text: "E segue perseguindo a meta: a carta não muda a meta nem o mandato.",
      bend: 0,
    },
  ],
  steps: [{ id: "all", label: "Tudo", groups: [], title: "A meta", intro: "" }],
};

export const minimumWageSpec: DiagramSpec = {
  height: 340,
  width: 740,
  label:
    "Diagrama da regra de reajuste do salário mínimo: INPC mais o crescimento do PIB de dois anos antes, com o ganho real limitado pelo arcabouço fiscal",
  groupColors: { inflation: "var(--loop-inflation)", growth: "var(--bridge-rate)" },
  nodes: [
    {
      id: "inpc",
      title: "INPC",
      subtitle: "12 meses até novembro do ano anterior",
      concept: "inpc",
      accent: "var(--loop-inflation)",
      x: 10,
      y: 30,
    },
    {
      id: "gdp",
      title: "PIB de dois anos antes",
      subtitle: "crescimento real",
      concept: "gdp",
      accent: "var(--bridge-rate)",
      x: 10,
      y: 220,
    },
    {
      id: "cap",
      title: "Limite do arcabouço",
      subtitle: "de 2025 a 2030, no máximo 2,5%",
      x: 280,
      y: 220,
    },
    {
      id: "raise",
      title: "Reajuste",
      subtitle: "multiplica as duas partes",
      x: 280,
      y: 30,
    },
    {
      id: "wage",
      title: "Salário mínimo de 2026",
      value: "R$ 1.621",
      subtitle: "desde 1º de janeiro de 2026",
      concept: "minimum-wage",
      x: 550,
      y: 30,
    },
  ],
  edges: [
    {
      from: "inpc",
      to: "raise",
      group: "inflation",
      text: "O INPC repõe a inflação de quem ganha de 1 a 5 mínimos: em 2026, 4,18%.",
      bend: 0,
    },
    {
      from: "gdp",
      to: "cap",
      group: "growth",
      text: "O crescimento real do PIB de dois anos antes dá o ganho real (Lei 14.663/2023).",
      bend: 0,
    },
    {
      from: "cap",
      to: "raise",
      group: "growth",
      text: "De 2025 a 2030, esse ganho fica dentro da faixa de crescimento do gasto do arcabouço fiscal, que vai até 2,5% (Lei 15.077/2024, art. 4º). O PIB de 2024 cresceu mais que isso, então valeu o teto.",
      bend: 0,
    },
    {
      from: "raise",
      to: "wage",
      group: "inflation",
      text: "As duas partes se multiplicam: 1,0418 × 1,025 = 1,0678. Sobre os R$ 1.518 de 2025, dá R$ 1.621, arredondado para o real inteiro: um reajuste de 6,79%.",
      bend: 0,
    },
  ],
  steps: [{ id: "all", label: "Tudo", groups: [], title: "A regra", intro: "" }],
};
