"""create inflation tolerances

Revision ID: da3dcae65266
Revises: e40b52257d4a
Create Date: 2026-10-08 23:00:57.766210
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "da3dcae65266"
down_revision: str | Sequence[str] | None = "e40b52257d4a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inflation_tolerances",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("width", sa.Double[float](), nullable=False),
        sa.PrimaryKeyConstraint("year", name=op.f("pk_inflation_tolerances")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inflation_tolerances")
    # ### end Alembic commands ###
